# Generated by Django 4.1.3 on 2022-12-05 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='tipo',
        ),
        migrations.AddField(
            model_name='modelo',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Produto', to='core.produto'),
            preserve_default=False,
        ),
    ]
