# Generated by Django 4.1.3 on 2022-12-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marca_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='cnpj',
        ),
    ]
