# Generated by Django 4.1.3 on 2022-12-05 04:38

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_marca_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(default=0, max_length=18),
            preserve_default=False,
        ),
    ]
