# Generated by Django 4.1.3 on 2022-12-06 12:42

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_marca_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='imagem',
            field=stdimage.models.StdImageField(default=0, force_min_size=False, upload_to='modelo', variations={'thumbnail': {'height': 667, 'width': 1000}}),
            preserve_default=False,
        ),
    ]
