# Generated by Django 4.1.3 on 2022-12-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modelo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='texto',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
