# Generated by Django 4.1.3 on 2022-12-07 00:31

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelo_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=500)),
                ('preco', models.FloatField()),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='modelo', variations={'thumbnail': {'height': 667, 'width': 1000}})),
                ('texto', models.TextField(max_length=1000)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Marca_Notebook', to='core.marca')),
            ],
            options={
                'verbose_name': 'Notebook',
                'verbose_name_plural': 'Notebook',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Smartphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=500)),
                ('preco', models.FloatField()),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='modelo', variations={'thumbnail': {'height': 667, 'width': 1000}})),
                ('texto', models.TextField(max_length=1000)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Marca_Smartphone', to='core.marca')),
            ],
            options={
                'verbose_name': 'Smartphone',
                'verbose_name_plural': 'Smartphones',
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
