# Generated by Django 4.1.3 on 2022-12-07 01:01

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notebook_smartphones_delete_modelo_delete_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='notebookpics', variations={'thumbnail': {'crop': True, 'height': 600, 'width': 600}}),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='smartphonepics', variations={'thumbnail': {'crop': True, 'height': 667, 'width': 1000}}),
        ),
    ]
