# Generated by Django 4.1.3 on 2022-12-07 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_notebook_imagem_alter_smartphones_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='cliente',
            field=models.ManyToManyField(blank=True, related_name='cursos_aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
