# Generated by Django 4.1.3 on 2022-12-07 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_smartphones_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='cliente',
            field=models.ManyToManyField(blank=True, related_name='cliente_notebook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notebook',
            name='estoque',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphones',
            name='estoque',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='cliente',
            field=models.ManyToManyField(blank=True, related_name='cliente_smartphone', to=settings.AUTH_USER_MODEL),
        ),
    ]
